/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { Card } from "@/components/card";
import Script from "next/script";
import { Footer } from "@/components/footer";

import { Post } from "@/components/Box/post";
import {
  Education,
  Experience,
  Information,
  MyProjectCard,
  Profile,
  TechStack,
  Theme,
} from "@/components/Box";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {
  const [profile, setProfile] = useState<any>({});
  const [repos, setRepos] = useState([]);

  useEffect(() => {
    (async () => {
      const { data } = await axios.get("https://api.github.com/users/snmtriet");
      setProfile(data);
      const repos = await axios.get(
        "https://api.github.com/users/snmtriet/repos"
      );
      setRepos(repos.data);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://avatars.githubusercontent.com/u/75319942?v=4"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossOrigin="anonymous"
      ></Script>

      <div className="fade-in h-screen">
        <div className="p-4 lg:p-10 min-h-full bg-base-300">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 rounded-box">
            <div className="col-span-1">
              <div className="grid grid-cols-1 gap-6">
                <Theme />
                <Profile profile={profile} />
                <Information />
                <TechStack />
                <Experience />
                <Education />
              </div>
            </div>
            <div className="lg:col-span-2 col-span-1">
              <div className="grid grid-cols-1 gap-6">
                <div className="col-span-1 lg:col-span-2">
                  <div className="grid grid-cols-2 gap-6">
                    <div className="col-span-2">
                      <div className="card compact bg-base-100 shadow bg-opacity-40">
                        <div className="card-body">
                          <div className="mx-3 flex items-center justify-between mb-2">
                            <h5 className="card-title">
                              <span className="opacity-70 text-base-content">
                                GitHub Projects
                              </span>
                            </h5>
                            <a
                              href={profile?.html_url}
                              className="opacity-50 text-base-content"
                            >
                              See all
                            </a>
                          </div>
                          <div className="col-span-2">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                              {repos &&
                                repos.length > 0 &&
                                repos.map((item: any) => {
                                  return <Card key={item.id} item={item} />;
                                })}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-span-1 lg:col-span-2">
                  <div className="grid grid-cols-2 gap-6">
                    <div className="col-span-2">
                      <div className="card compact bg-base-100 shadow bg-opacity-40">
                        <div className="card-body">
                          <div className="mx-3 flex items-center justify-between mb-2">
                            <h5 className="card-title">
                              <span className="text-base-content opacity-70">
                                My Projects
                              </span>
                            </h5>
                          </div>
                          <div className="col-span-2">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                              <MyProjectCard name="SleepGangZ" />
                              <MyProjectCard name="Coin Game" />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-span-1 lg:col-span-2">
                  <div className="grid grid-cols-2 gap-6">
                    <div className="col-span-2">
                      <div className="card compact bg-base-100 shadow bg-opacity-40">
                        <div className="card-body">
                          <div className="mx-3 mb-2">
                            <h5 className="card-title">
                              <span className="text-base-content opacity-70">
                                Recent Posts
                              </span>
                            </h5>
                          </div>
                          <div className="col-span-2">
                            <div className="grid grid-cols-1 gap-6">
                              <Post />
                              <Post />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
